services:
  nginx:
    build: requirements/nginx/
    image: inception-nginx:1.0
    container_name: nginx
    ports:
      - "8443:443"
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

  mariadb:
    secrets:
      - db_password
      - db_root_password
    build: requirements/mariadb/
    image: inception-mariadb:1.0
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    build: requirements/wordpress/
    image: inception-wordpress:1.0
    container_name: wordpress
    environment:
      # Database connection (read from .env file)
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      # WordPress configuration
      - WORDPRESS_TITLE=${WP_TITLE}
      - WORDPRESS_ADMIN_USER=${WP_ADMIN_USER}
      - WORDPRESS_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WORDPRESS_USER=${WP_USER}
      - WORDPRESS_USER_EMAIL=${WP_USER_EMAIL}
      - WORDPRESS_URL=https://localhost:8443


    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/mysql"
  wordpress_vol:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/wordpress"

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

networks:
  inception:
    driver: bridge
