services:
  nginx:
    build: requirements/nginx/
    image: inception-nginx:1.0
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress

  mariadb:
    build: requirements/mariadb/
    image: inception-mariadb:1.0
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: requirements/wordpress/
    image: inception-wordpress:1.0
    container_name: wordpress
    environment:
      # Database connection (read from .env file)
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      # WordPress configuration
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DEBUG=false
      - WORDPRESS_URL="https://nde-vant.42.fr"
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/mysql"
  wordpress_vol:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/${USER}/data/wordpress"

networks:
  inception:
    driver: bridge
