
services:
  # web:
  #   build: requirements/nginx/
  #   container_name: nginx
    
  db:
    build: requirements/mariadb/
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/${USER}/data/mysql:/var/lib/mysql


  app:
    build: requirements/wordpress/
    container_name: wordpress
    volumes:
      - /home/${USER}/data/wordpress:/var/www/html
    