services:
  web:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress_vol:/var/www/html
    networks:
      - inception
    
  db:
    build: requirements/mariadb/
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception


  app:
    build: requirements/wordpress/
    container_name: wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=mariadb
    volumes:
      - wordpress_vol:/var/www/html  
    networks:
      - inception


volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/${USER}/data/mysql'
  wordpress_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/${USER}/data/wordpress'


networks:
  inception:
    driver: bridge